### ISSUE TITLE
Bigtop research

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#1]
## Description
Bigtop is an Apache Foundation project for Infrastructure Engineers and Data Scientists looking for comprehensive packaging, testing, and configuration of the leading open source big data components. Bigtop supports a wide range of components/projects, including, but not limited to, Hadoop, HBase and Spark.

## Tasks
- Research stable version of Bigtop, check critical issues in [JIRA](https://issues.apache.org/jira/projects/BIGTOP/issues/BIGTOP-3902?filter=allopenissues)
- Research [Bigtop repository structure](https://github.com/TNTU-RS-internship/bigtop)
- Research how to build Hadoop artifacts
- #2
- #3 
- Research tests implementation (for specific artifact and for entire assembly)

## Reqirements
- Stable versions of Bigtop, HDFS, YARN. Hive and Spark 3 for Ubuntu 22.04
- Assembly must support Python 3

**Comment by Nazarii-Melnyk** [comment]
Considering that support for Ubuntu 22.04 appeared only in versions 3.2.0 and 3.2.1, I think it makes sense to consider these two versions. 

In addition, the documentation for release 3.2.0 states the following known problem:

> The python dependency issues on `Ubuntu-22.04`, which caused the [smoke tests](https://ci.bigtop.apache.org/view/3.2.0-smoke-tests/job/Bigtop-3.2.0-ubuntu-22.04-smoke-tests/) of  `Ambari`, gpdb, `Hive`, Ycsb and Zeppelin to fail.

This problem was fixed in release 3.2.1. Linked [issue](https://issues.apache.org/jira/browse/BIGTOP-3930) and [PR](https://github.com/apache/bigtop/pull/1114)
So I propose to research latest version of bigtop - v3.2.1.

**Comment by Nazarii-Melnyk** [comment]
There are bug with zookeeper, that will be fixed in 3.3.0 Bigtop version. Linked [issue BIGTOP-3913](https://issues.apache.org/jira/browse/BIGTOP-3913) and [PR 1090](https://github.com/apache/bigtop/pull/1090/files). Also linked another [issue BIGTOP-4007](https://issues.apache.org/jira/browse/BIGTOP-4007) and it's [PR 1179](https://github.com/apache/bigtop/pull/1179)

**Comment by Nazarii-Melnyk** [comment]
Considering the following issue [BIGTOP-4052](https://issues.apache.org/jira/browse/BIGTOP-4052), I am more than sure that Bigtop artifacts supports Python 3, but there are several dependencies on python 2 that they are going to remove in the version 3.3.0.

**Comment by ya6lis** [comment]
- bigtop-bigpetstore : BigPetStore is a family of example applications for the Hadoop/Spark ecosystems. BigPetStore generates and analyzes synthetic transaction data for a fictional chain of petstores.
- bigtop-ci : Bigtop's CI approach relies heavily on the Groovy DSL Job plugin in Jenkins, simplifying configuration to keep it stateless. README file includes all require plugins from Jenkins.
- bigtop-data-generators :  A collection of synthetic data generators and supporting libraries for building blueprints, smoke testing, and timing operations. Includes data generators and libraries. 
- bigtop-deploy : Deployment scripts and puppet stuff for Apache Bigtop.
- bigtop-packages : RPM/DEB specifications for Apache Bigtop subcomponents.
- bigtop-test-framework : The source code for the iTest utilities (framework used by smoke tests).
- bigtop-tests :
    - cloud-weather-report: [Cloud Weather Report (cwr)](https://github.com/juju-solutions/cloud-weather-report/) enables charm 
    authors and maintainers to run health checks and benchmarks on multiple clouds using [Juju] 
    (https://jujucharms.com/docs/stable/getting-started).
    - smoke-test: Gradle based test framework aims at making it extremely simple to customize and test Apache BigTop's hadoop 
    distribution.
    - test-artifacts : Source for tests. Contains Hadoop stack tests such as smokes, load, etc.
    - test-execution : Maven pom drivers for running the integration tests found in test-artifacts.
- bigtop-toolchain : Puppet scripts for setting up an instance which can build Apache Bigtop, sets up utils like jdk/maven/protobufs/...
- docker : Dockerfiles and Docker Sandbox build scripts.
- gradle : Include gradle-wrapper properties
- provisioner : Docker Provisioner that automatically with one click.
- src : All files that are related to the main site - https://bigtop.apache.org/
- test : Files that are related to ITest

**Comment by Nazarii-Melnyk** [comment]
### Note on LC_ALL/LANG

Compilation may fail if your locale is not in english. You might for example
see some strange errors with dpkg-buildpackage. In that case, you should reset
the language variables before compiling:

LC_ALL=C; export LC_ALL
LANG=C; export LANG
./gradlew deb

#### source: /BUILDING.txt file

**Comment by ya6lis** [comment]
Considering to official [wiki]https://cwiki.apache.org/confluence/display/BIGTOP/Bigtop+3.2.1+Release we should use  HDFS – 3.3.5, YARN - version bundled with Hadoop 3.3.5, Hive – 3.1.3 and Spark 3.2.1
