### ISSUE TITLE
Research CI/CD

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#12]
## Tasks
- Research Jenkins and CI/CD stages

## Results
- [x] @Nazarii-Melnyk 
- [x] @ya6lis

**Comment by Nazarii-Melnyk** [comment]
Required versions of java, supported by LTS Jenkins releases:
![image](https://github.com/TNTU-RS-internship/bigtop/assets/72742712/9d14869a-72c8-42f0-9439-45a410810068)

**Comment by ya6lis** [comment]
Heres a usefull [link](https://cwiki.apache.org/confluence/display/BIGTOP/Bigtop+CI+Setup+Guide) for Bigtop CI setup.
Also should be usefull to try implements CI/CD process from official Jenkins [tutorial](https://www.jenkins.io/doc/tutorials/)

**Comment by Nazarii-Melnyk** [comment]
There are problems with vulnerability in [Matrix Reloaded plubgin](https://plugins.jenkins.io/matrix-reloaded/)

![Image](https://github.com/TNTU-RS-internship/bigtop/assets/72742712/ec2e040c-2670-4272-8bb6-6f42756ad079)

**Comment by Nazarii-Melnyk** [comment]
[SSH Slaves plugin](https://wiki.jenkins-ci.org/JENKINS/SSH-Slaves-plugin.html) is deprecated. It is replaced by [SSH Build Agents](https://plugins.jenkins.io/ssh-slaves/)
