### ISSUE TITLE
Resource requirements

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#4]
## Tasks
- [x] Research how much CPU, disk space and RAM assembly requires different stages

**Comment by Nazarii-Melnyk** [comment]
### CPU
To build assembly with hadoop, hive, spark and zookeeper repo-in-docker locally there are enough 4 CPU cores. Results of build:
- hadoop, hive, spark, zookeeper -  ~2h 40min

### Disk space
In documentation for hadoop build minimal requirement - ~20 GB of free disk space, but recommended some more.

But for every node there are required this minimal space. Minimal nodes there are needed - 3. 

Also for tests may be required some free space, so I think 100 GB free space will be good to have.

### RAM
For build required 8 GB. But I think will be good to have some more memory for tests - 12 GB.

**Comment by Nazarii-Melnyk** [comment]
@RomanButsiy 
Привіт ✋ 
Щодо серверів, я думаю для білду і тестування збірки можна виділити одну машину з такими характеристиками:
- ОС - Ubuntu 22.04;
- CPU - 8 ядер
- RAM - 16 ГБ
- Вільний дисковий простір - 200 ГБ

І ще звпитання, чи буде можливість змінити обсяг вільного місця? Це єдиний пункт в якому я не впевнений, можливо 200 ГБ це вже забагато, тому що збірка сама по собі небагато займає, але наскільки багато ресурсів з'їдатимуть тести на жаль не можу сказати.


За інший сервер для деплою поки ще не можу сказати, потрібно ще посидіти розібратись як має працювати CI/CD джоба для цього

**Comment by RomanButsiy** [comment]
@Nazarii-Melnyk 
Hi ✋
It's possible to adjust the RAM and the number of CPUs as needed without any limitations, but disk size can only be increased, not decreased

The instance is now available at:
```bash
ssh ubuntu@10.216.14.10
```

**Comment by Nazarii-Melnyk** [comment]
@RomanButsiy Hi Roman ✋ 
After the agent instance was added, since all jobs are executed on it, the need for a lot of resources on jenkins-master disappeared.
So, on instance `10.216.14.10` num of CPU can be downgraded to 2 (instead 8) and RAM can be downgraded to 8 GB (instead 16).

Also to add more parallel executions on instance `10.216.14.11` I propose to increase num of CPU to 12 and RAM to 32 GB
